global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DAM Backend services
  - job_name: 'dam-backend'
    static_configs:
      - targets: ['dam-backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Nginx metrics (if nginx-module-vts is installed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['dam-nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['dam-database:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['dam-redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Docker Swarm metrics
  - job_name: 'docker-swarm'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 15s
